In [37]:
import os
import IPython.display as ipd
import pandas as pd
import matplotlib.pylab as plt
import cv2
import numpy as np

In [31]:
cd ~/Documents/Git/fastai/train_sample_videos


C:\Users\leon_\Documents\Git\fastai\train_sample_videos


In [32]:
train_sample_metadata = pd.read_json('metadata.json').T
#train_sample_metadata
#test = ipd.Video("aassnaulhq.mp4", embed=True)

In [33]:
video_file = 'akxoopqjqz.mp4'

cap = cv2.VideoCapture(video_file)

frames = []
while(cap.isOpened()):
    ret, frame = cap.read()
    if ret==True:
        frames.append(frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
cap.release()

print('The number of frames saved: ', len(frames))



The number of frames saved:  300


In [46]:
test = frames

nptest = np.asarray(test)

# All frames in one vector
nptest = nptest.reshape((300,1920*1080*3))

In [61]:
# Project Frame differences

np.shape(nptest)

nptestdiff = np.diff(nptest)

nptestdiff2 = nptest[1:len(nptest)]-nptest[0:len(nptest)-1]


In [69]:
print(np.shape(nptestdiff2))

print(nptest[1][3])
print(nptest[1][4])
print(nptestdiff2[1][4])
print(nptest[1:5][1:5])
print("-----------------------------------")
print(nptestdiff2[1:4][1:4])


(299, 6220800)
140
165
0
[[140 165 166 ...  77  95 102]
 [140 165 166 ...  76  94 101]
 [140 166 164 ...  77  95 102]]
-----------------------------------
[[  0   0   0 ... 255 255 255]
 [  0   1 254 ...   1   1   1]]


In [75]:
test255 = np.zeros((len(nptestdiff2),1))
for i in range(0,len(nptestdiff2)):
    test255[i] = [x-255 for x in nptestdiff2[i] if x > 127]

ValueError: cannot copy sequence with size 144151 to array axis with dimension 1

In [86]:
# project flatten

a = frames
a = np.asarray(a)
b = []
for i in range(1,5):#len(frames)):
    d = np.ndarray.flatten(a[i]) - np.ndarray.flatten(a[i-1])
    d = [x - 255 for x in d if x > 127]
    b.append(d)
    print("Current iteration: ", i)
#a = np.ndarray.flatten(a)

Current iteration:  1
Current iteration:  2
Current iteration:  3
Current iteration:  4


In [88]:
print(np.shape(b))
print(b[1:4][1:4])

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [34]:
print(len(frames[1][1]))
print(len(frames[1][2]))
print(len(frames[1]))

1920
1920
1080


In [21]:
ls = []
for file in os.listdir("train_sample_videos/"):
    if file.endswith(".mp4"):
        ls.append(file)
#print(ls)

In [24]:
ls[0:1]
print(ls[0])

aagfhgtpmv.mp4


In [27]:
def frame_loader(video):
    
    cap = cv2.VideoCapture(video)

    frames = []
    while(cap.isOpened()):
        ret, frame = cap.read()
        if ret==True:
            frames.append(frame)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
        else:
            break
    cap.release()
    #for frame in frames:
        

    print('The number of frames saved: ', len(frames))

def iterator(liste):
    frames = []
    for video_file in liste:
        #video_file = 'akxoopqjqz.mp4'
        frames.append([video_file, frame_loader(video_file)])
    return frames
        


In [28]:
all_frames = frame_loader(ls[0])

The number of frames saved:  0


In [14]:
print(len(frames))
print(len(frames[1]))
print(len(frames[1][1]))
print(len(frames[1][1][1]))

x = range(0,len(frames))
i = 0
indeces = [[],[]]
for n in x: 
    if n%2 == 0:
        indeces[0].append(i)
        j = i + 1
        indeces[1].append(j)
    i+=1

300
1080
1920
3


In [16]:
print(len(frames[0])

[[[140 165 166]
  [140 165 166]
  [140 165 166]
  ...
  [106 132 135]
  [104 130 133]
  [101 127 130]]

 [[140 165 166]
  [140 165 166]
  [140 165 166]
  ...
  [104 130 133]
  [103 129 132]
  [101 127 130]]

 [[140 165 166]
  [140 165 166]
  [140 165 166]
  ...
  [101 127 130]
  [103 129 132]
  [103 129 132]]

 ...

 [[102 123 127]
  [102 123 127]
  [102 123 127]
  ...
  [ 75  95 102]
  [ 75  95 102]
  [ 75  95 102]]

 [[102 123 127]
  [102 123 127]
  [102 123 127]
  ...
  [ 75  95 102]
  [ 75  95 102]
  [ 75  95 102]]

 [[101 122 126]
  [101 122 126]
  [101 122 126]
  ...
  [ 75  95 102]
  [ 75  95 102]
  [ 75  95 102]]]
